### ISSUE TITLE
Adding support for injecting on system internal .md paragraphs files

### ISSUE THREAD

**Issue by MikeLemo1** [fire1ce/pypi-publishing-actions#3]
I was wondering how easy would it be to add support for injecting specific paragraphs from a local .md file similar to how this works now but with the ability to do similar stuff like: 

`{{ external_markdown('index.md', '## Installation') }}`

Where do you start?

**Comment by fire1ce** [comment]
use mkdocs for local files. 
not planned

**Comment by MikeLemo1** [comment]
Yeah Couldn't find a solution that injects only a certain paragraph I tried using external_markdown with mkdocs which works with the included example of the hosted github page but not for local files you probably know best why :D .
